### PR TITLE
[DEV-15633] Support random jitter for local cache expiration

### PR DESCRIPTION
**Pull request by bal2ag**

### CODE REVIEW

**Comment by rmtobin** [comment]
@bal2ag This could probably use some unit tests

**Comment by bal2ag** [comment]
@rmtobin added unit tests

**Review by rmtobin — APPROVED** [review]
This looks good. 👍

**Comment by rmtobin** [comment]
@bal2ag Don't forget to update the sha in `requirements.txt` in the web repo.

**Comment by bal2ag** [comment]
@rmtobin actually there's a gargoyle change to use this new param as well, then one more change in the webapp to update the SHA for both gargoyle and django-modeldict and pass in the new max jitter param via settings, I'll be sending them your way soon!

**Pull request merged**
